Chennai/urls.py
from django.urls import path
from Chennai.views import *
app_name='Chennai'

urlpatterns=[
    path('Dhoni/',Dhoni,name='Dhoni'),
    path('Suresh/',Suresh,name='Suresh'),
]

Mumbai/urls.py
from django.urls import path
from Mumbai.views import *
app_name='Mumbai'

urlpatterns=[
    path('Rohit/',Rohit,name='Rohit'),
    path('Suryakumar/',Suryakumar,name='Suryakumar'),
]

project15/urls.py
from django.contrib import admin
from django.urls import path,include
import Chennai,Mumbai

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Chennai/',include('Chennai.urls')),
    path('Mumbai/',include('Mumbai.urls')),
]

Chennai/models.py
from django.db import models

# Create your models here.

Mumbai/models.py
from django.db import models

# Create your models here.

Chennai/views.py
from django.shortcuts import render

# Create your views here.
def Dhoni(request):
    return render(request,'Dhoni.html')

def Suresh(request):
    return render(request,'Suresh.html')

Mumbai/views.py
from django.shortcuts import render

# Create your views here.
def Rohit(request):
    return render(request,'Rohit.html')

def Suryakumar(request):
    return render(request,'Suryakumar.html')

templates/Dhoni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>MS Dhoni</h1>
        <h1>This is Dhoni html page</h1>
        <h1>This page belongs to Chennai</h1>
        <a href="{% url 'Mumbai:Rohit' %}">Go to Rohit page</a>
    </center>
</body>
</html>

templates/Rohit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Rohit Sharma</h1>
        <h1>This is Rohit html page</h1>
        <h1>This page belongs to Mumbai</h1>
        <a href="{% url 'Chennai:Dhoni' %}">Go to Dhoni page</a>
    </center>
</body>
</html>

templates/Suresh.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Suresh Raina</h1>
        <h1>This is Suresh html page</h1>
        <h1>This page belongs to Chennai</h1>
        <a href="{% url 'Mumbai:Suryakumar' %}">Go to Suryakumar page</a>
    </center>
</body>
</html>

templates/Suryakumar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Suryakumar Yadav</h1>
        <h1>This is Suryakumar html page</h1>
        <h1>This page belongs to Mumbai</h1>
        <a href="{% url 'Chennai:Suresh' %}">Go to Suresh page</a>
    </center>
</body>
</html>